- name: Setup DevOps Environment
  hosts: localhost
  become: yes
  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started

    #- name: Install kubectl
    #  apt:
      #  name: kubectl
      #  state: present
       # update_cache: yes