name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Debug - List Files
      run: ls -R

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        cd smart-app || exit 1
        npm install

    - name: Build Docker Image
      run: docker build -t smart-app ./smart-app